//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activities.ExcelDiagram.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activities.ExcelDiagram.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активность предназначена для создания столбчатой диаграммы по указанному диапазону таблицы Excel.
        /// </summary>
        internal static string Activities_Description {
            get {
                return ResourceManager.GetString("Activities_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первая ячейка.
        /// </summary>
        internal static string Cell1_Description {
            get {
                return ResourceManager.GetString("Cell1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ячейка 1.
        /// </summary>
        internal static string Cell1_ScreenName {
            get {
                return ResourceManager.GetString("Cell1_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вторая ячейка.
        /// </summary>
        internal static string Cell2_Description {
            get {
                return ResourceManager.GetString("Cell2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ячейка 2.
        /// </summary>
        internal static string Cell2_ScreenName {
            get {
                return ResourceManager.GetString("Cell2_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание столбчатой диаграммы в Excel.
        /// </summary>
        internal static string ExcelDiagram_ScreenName {
            get {
                return ResourceManager.GetString("ExcelDiagram_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер листа в excel (начинается с 1).
        /// </summary>
        internal static string NumberSheet_Description {
            get {
                return ResourceManager.GetString("NumberSheet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер листа excel.
        /// </summary>
        internal static string NumberSheet_ScreenName {
            get {
                return ResourceManager.GetString("NumberSheet_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кастомные активности.
        /// </summary>
        internal static string PathActivities {
            get {
                return ResourceManager.GetString("PathActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь до входящего файла Excel.
        /// </summary>
        internal static string PathFile_Description {
            get {
                return ResourceManager.GetString("PathFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь к файлу.
        /// </summary>
        internal static string PathFile_ScreenName {
            get {
                return ResourceManager.GetString("PathFile_ScreenName", resourceCulture);
            }
        }
    }
}
